import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { prompt } = await req.json()
    
    if (!prompt) {
      throw new Error('Prompt is required')
    }

    const geminiApiKey = Deno.env.get('GEMINI_API_KEY')
    if (!geminiApiKey) {
      throw new Error('GEMINI_API_KEY not configured')
    }

    console.log('Generating module with prompt:', prompt)

    // Call Gemini API to generate module content
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${geminiApiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: `Create a comprehensive learning module based on this prompt: "${prompt}".

Please generate a structured JSON response with the following format:
{
  "title": "Module Title",
  "description": "Brief description of the module",
  "learning_outcomes": ["outcome 1", "outcome 2", "outcome 3"],
  "sections": [
    {
      "title": "Section Title",
      "content": "Detailed content for this section",
      "type": "content"
    },
    {
      "title": "Quiz: Section Name",
      "questions": [
        {
          "question": "Question text",
          "options": ["option 1", "option 2", "option 3", "option 4"],
          "correct": 0,
          "explanation": "Why this is correct"
        }
      ],
      "type": "quiz"
    }
  ],
  "estimated_duration": "30 minutes",
  "prerequisites": ["prerequisite 1", "prerequisite 2"]
}

Make the content engaging, practical, and appropriate for the specified difficulty level. Include at least 3-4 content sections and 2 quiz sections with multiple choice questions. Focus on real-world applications and examples.`
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.8,
          maxOutputTokens: 4000,
        },
      }),
    })

    if (!response.ok) {
      const errorData = await response.text()
      console.error('Gemini API error:', errorData)
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    console.log('Gemini API response received')

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text
    
    if (!generatedText) {
      throw new Error('No content generated from Gemini API')
    }

    // Parse the JSON response from Gemini
    let moduleData
    try {
      // Extract JSON from the response (Gemini sometimes wraps it in markdown)
      const jsonMatch = generatedText.match(/```json\n([\s\S]*?)\n```/) || 
                       generatedText.match(/```\n([\s\S]*?)\n```/) ||
                       [null, generatedText]
      
      const jsonString = jsonMatch[1] || generatedText
      moduleData = JSON.parse(jsonString.trim())
    } catch (parseError) {
      console.error('Failed to parse JSON from Gemini response:', parseError)
      // Create a fallback structure
      moduleData = {
        title: "AI Generated Module",
        description: "Learning module generated by AI",
        learning_outcomes: ["Understand key concepts", "Apply knowledge practically"],
        sections: [
          {
            title: "Introduction",
            content: generatedText.substring(0, 500),
            type: "content"
          }
        ],
        estimated_duration: "30 minutes",
        prerequisites: []
      }
    }

    console.log('Module data generated successfully')

    return new Response(
      JSON.stringify({ moduleData }),
      { 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    )

  } catch (error: any) {
    console.error('Error in generate-module function:', error)
    
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Failed to generate module',
        details: error.toString()
      }),
      { 
        status: 500,
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        }
      }
    )
  }
})