// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzttqloyamcivctsfxkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6dHRxbG95YW1jaXZjdHNmeGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzE5MDIsImV4cCI6MjA3MTU0NzkwMn0.kOaKsCgwsWYLWbloN1haekp5aJ0Fn2pfaYIgOyv3ENQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});